# https://houndci.com/configuration
fail_on_violations: true
ruby:
  config_file: .rubocop.yml
coffeescript:
  config_file: coffeelint.json
jshint:
  enabled: false
eshint:
  enabled: true
  config_file: .eslintrc
  ignore_file: .eslintignore
scss:
  config_file: .scss-lint.yml
