language: ruby
rvm:
  - 2.3.1
bundler_args: --without development
before_script:
  - psql -c "create database $DATABASE_NAME;" -U $DATABASE_USERNAME
  - bundle exec rake db:migrate
script:
  - bundle exec rake test
