language: ruby
cache: bundler
rvm:
  - 2.3.1
bundler_args: --without development
services:
  - postgresql
addons:
  postgresql: "9.5.3"
before_script:
  - psql -c "create database $DATABASE_NAME;" -U $DATABASE_USERNAME
  - bundle exec rake db:migrate
script:
  - bundle exec rake test
