# References:
# - https://docs.travis-ci.com/user/database-setup/#PostgreSQL
# - https://docs.travis-ci.com/user/caching/#Bundler
language: ruby
cache: bundler
rvm:
  - 2.3.1
bundler_args: --without development
services:
  - postgresql
addons:
  # NOTE: Current latest available version of Postgres on Travis is 9.4.1
  postgresql: "9.4"
before_script:
  - psql -c "create database $DATABASE_NAME;" -U $DATABASE_USERNAME
  - bundle exec rails db:migrate
script:
  - bundle exec rails test
