defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *defaults
  database: <%= Rails.application.secrets.app_database_name %>
  username: <%= Rails.application.secrets.app_database_username %>
  password: <%= Rails.application.secrets.app_database_password %>

test:
  <<: *defaults
  database: <%= Rails.application.secrets.app_database_name %>
  username: <%= Rails.application.secrets.app_database_username %>
  password: <%= Rails.application.secrets.app_database_password %>

production:
  <<: *defaults
  database: <%= Rails.application.secrets.app_database_name %>
  username: <%= Rails.application.secrets.app_database_username %>
  password: <%= Rails.application.secrets.app_database_password %>
