# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database_name: <%= ENV["DATABASE_NAME"] %>
  database_username: <%= ENV["DATABASE_USERNAME"] %>

# NOTE: Since these config values need to be used both locally and on remote
# CI, these ENV values will come from either .env.test locally, or directly
# from Travis if tests run on CI.
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database_name: <%= ENV["DATABASE_NAME"] %>
  database_username: <%= ENV["DATABASE_USERNAME"] %>

# NOTE: These ENV values will currently come from Heroku.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database_name: <%= ENV["DATABASE_NAME"] %>
  database_username: <%= ENV["DATABASE_USERNAME"] %>
  database_password: <%= ENV["DATABASE_PASSWORD"] %>
